# Generated by Django 5.0.1 on 2024-06-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_telegramusers_audios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
